import type { Metadata } from "next";
import { Inter, Poppins, Sora } from "next/font/google";
import { FC } from "react";

import { AuthProvider } from "@/components";
import { IChildren } from "@/interface";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Life Change BD",
  description: "Generated by Baitul Hikmah Team",
};

const RootLayout: FC<IChildren> = ({ children }) => (
  <html lang="en">
    <body className={`${(inter.className, poppins.className, sora.className)}`}>
      <AuthProvider>{children}</AuthProvider>
    </body>
  </html>
);

export default RootLayout;
